"""Initial migration

Revision ID: 79637a97449f
Revises: None
Create Date: 2026-05-31 12:18:09.597041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.db.base_class

# revision identifiers, used by Alembic.
revision: str = '79637a97449f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', app.db.base_class.GUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', app.db.base_class.GUID(), nullable=False),
    sa.Column('user_id', app.db.base_class.GUID(), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('details', sa.String(length=1000), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('doctors',
    sa.Column('id', app.db.base_class.GUID(), nullable=False),
    sa.Column('user_id', app.db.base_class.GUID(), nullable=False),
    sa.Column('specialty', sa.String(length=255), nullable=False),
    sa.Column('license_number', sa.String(length=100), nullable=False),
    sa.Column('bio', sa.String(length=1000), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=False),
    sa.Column('consultation_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('verification_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_number'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_doctors_specialty'), ['specialty'], unique=False)

    op.create_table('patients',
    sa.Column('id', app.db.base_class.GUID(), nullable=False),
    sa.Column('user_id', app.db.base_class.GUID(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('blood_group', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('availability_slots',
    sa.Column('id', app.db.base_class.GUID(), nullable=False),
    sa.Column('doctor_id', app.db.base_class.GUID(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('is_booked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('availability_slots', schema=None) as batch_op:
        batch_op.create_index('idx_slots_doctor_time', ['doctor_id', 'start_time', 'is_booked'], unique=False)

    op.create_table('family_members',
    sa.Column('id', app.db.base_class.GUID(), nullable=False),
    sa.Column('patient_id', app.db.base_class.GUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('relation', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saas_subscriptions',
    sa.Column('id', app.db.base_class.GUID(), nullable=False),
    sa.Column('doctor_id', app.db.base_class.GUID(), nullable=False),
    sa.Column('stripe_sub_id', sa.String(length=255), nullable=True),
    sa.Column('plan_name', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doctor_id'),
    sa.UniqueConstraint('stripe_sub_id')
    )
    op.create_table('appointments',
    sa.Column('id', app.db.base_class.GUID(), nullable=False),
    sa.Column('patient_id', app.db.base_class.GUID(), nullable=False),
    sa.Column('doctor_id', app.db.base_class.GUID(), nullable=False),
    sa.Column('slot_id', app.db.base_class.GUID(), nullable=False),
    sa.Column('appointment_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('payment_status', sa.String(length=50), nullable=False),
    sa.Column('appointment_type', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['slot_id'], ['availability_slots.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slot_id')
    )
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.create_index('idx_appointments_doctor', ['doctor_id'], unique=False)
        batch_op.create_index('idx_appointments_patient', ['patient_id'], unique=False)
        batch_op.create_index('idx_appointments_status', ['status'], unique=False)

    op.create_table('invoices',
    sa.Column('id', app.db.base_class.GUID(), nullable=False),
    sa.Column('appointment_id', app.db.base_class.GUID(), nullable=False),
    sa.Column('stripe_charge_id', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('platform_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('appointment_id'),
    sa.UniqueConstraint('stripe_charge_id')
    )
    op.create_table('prescriptions',
    sa.Column('id', app.db.base_class.GUID(), nullable=False),
    sa.Column('appointment_id', app.db.base_class.GUID(), nullable=False),
    sa.Column('notes', sa.String(length=2000), nullable=False),
    sa.Column('pdf_url', sa.String(length=1000), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('appointment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prescriptions')
    op.drop_table('invoices')
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_index('idx_appointments_status')
        batch_op.drop_index('idx_appointments_patient')
        batch_op.drop_index('idx_appointments_doctor')

    op.drop_table('appointments')
    op.drop_table('saas_subscriptions')
    op.drop_table('family_members')
    with op.batch_alter_table('availability_slots', schema=None) as batch_op:
        batch_op.drop_index('idx_slots_doctor_time')

    op.drop_table('availability_slots')
    op.drop_table('patients')
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_doctors_specialty'))

    op.drop_table('doctors')
    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
